#!/bin/bash
#  np: New Project build system
#  Run --help for arguments

rootdir=$(pwd) # Current root directory, for reference

check_pkg_manager() { # Check what package manager the user is running
  declare -A os_info;
  os_info[/etc/redhat-release]="\033[38;2;157;37;253myum\033[0m"
  os_info[/etc/arch-release]="\033[38;2;240;250;81mpacman\033[0m"
  os_info[/etc/gentoo-release]="\033[38;2;111;64;248memerge\033[0m"
  os_info[/etc/SuSE-release]="\033[38;2;82;250;112mzypp\033[0m"
  os_info[/etc/debian_version]="\033[38;2;236;2;52mapt\033[0m"
  os_info[/etc/alpine-release]="\033[38;2;7;217;247mapk\033[0m"

  for f in ${!os_info[@]}
  do
    if [[ -f $f ]]; then
      echo -e "Your package manager is: ${os_info[$f]}"
    fi
  done
}

# Function that checks if the necessary TUI components exist
check_if_tui_supported() {
  if hash dialog 2>/dev/null; then
    echo -e "TUI components exist. \x1b[38;2;0;100;0mLaunching with TUI\033[5m..."
    return 0
  else
    echo "It doesn't look like you have the dialog binary installed, which is required for the TUI. Would you like to:"
    echo "  0. Install the dialog binary via your package manager, and then proceed with the installation"
    echo "  1. Ignore and attempt to launch the TUI anyway (ONLY IF YOU KNOW WHAT YOU ARE DOING!!)"
    echo "  2. Proceed with the installation in a non-TUI way, similar to the way I'm communicating with you right now."
    echo "  3. Specify a custom location for the dialog binary (make sure you have its depencies installed!)"
  fi
}

if [ $# -eq 0 ]; then
  echo "No arguments supplied. Checking if project already exists..."
  if [ -f "$rootdir/.np/project.json" ]; then
    echo "Project already exists. Launching configuration screen..."
  fi
  echo ""
  read -p "No project exists in your current working directory. Would you like to create a new one? [Y/n] " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo "nuclear bomb diffused"
  fi
  echo
fi

check_if_tui_supported # After this is done executing, the user should have TUI components installed or they might install in "phonecall" mode.

echo -e "\x1b[0m"
exit 0